@startuml port

class Port {
  PortType type
  PortDirectionality directionality
  Port connectedTo

  Port port(PortType, PortDirectionality)
  boolean connect(Port)
  void disconnect(Boolean)
  String info()
}

@enduml
