@startuml Port
!theme amiga

class Port {
  - PortType type
  - PortDirectionality directionality
  - Port connectedTo

  + Port(PortType, PortDirectionality)
  + boolean connect(Port targetPort)
  + void disconnect(Boolean isRootCall)
  + String toString()
  + boolean equals(Object obj)
}

@enduml